(function(){
  const chapters=window.DECK||[]; let items=[{kind:'cover'}]; chapters.forEach(ch=>{items.push({kind:'chapter',ch});ch.slides.forEach(s=>items.push({kind:'slide',ch,s}))});
  let pos=0; const stage=document.querySelector('#stage'),toc=document.querySelector('#toc');
  const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function buildToc(){toc.innerHTML=`<div class="toc-title">五年級數學複習</div><button class="toc-item" data-i="0">封面與使用說明</button>`;chapters.forEach((ch,ci)=>{const start=items.findIndex(x=>x.kind==='chapter'&&x.ch===ch);const g=document.createElement('div');g.className='toc-group';g.innerHTML=`<h3 style="color:${ch.color}">${esc(ch.title)}</h3>`;g.innerHTML+=ch.slides.map((s,i)=>`<button class="toc-item" data-i="${start+i+1}">${esc(s.sec)}　${esc(s.secName)}</button>`).join('');toc.appendChild(g)});toc.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{pos=+b.dataset.i;render();toc.classList.remove('open')})}
  function slideShell(ch,body){const d=document.createElement('article');d.className='slide';d.style.setProperty('--chapter',ch.color);d.innerHTML=body;return d}
  function render(){stage.innerHTML='';const it=items[pos];if(it.kind==='cover'){stage.appendChild(slideShell({color:'#2563eb'},`<div class="cover slide"><div class="eyebrow">108 課綱國小數學・五年級</div><h1>五年級數學<br>上下學期全冊複習</h1><p>一頁一重點，左邊整理觀念，右邊用圖形與互動把答案看懂。</p><p class="note">本版採常見跨版本單元架構；可依實際課本再調整。使用 ← → 翻頁，或從目錄跳轉。</p></div>`))}else if(it.kind==='chapter'){stage.appendChild(slideShell(it.ch,`<div class="chapter slide" style="--chapter:${it.ch.color}"><div class="eyebrow">${esc(it.ch.term)}</div><h2>${esc(it.ch.title)}</h2><p>${esc(it.ch.subtitle)}</p></div>`))}else{const s=it.s,ch=it.ch;const points=s.points.map(x=>`<li>${x}</li>`).join('');const formula=s.formula?`<div class="formula"><small>${esc(s.formula.label)}</small><div>\\(${s.formula.tex}\\)</div></div>`:'';const ex=s.example?`<details class="example"><summary>例題：${s.example.q}</summary><div class="steps">${s.example.steps.map((x,i)=>`${i+1}. ${x}`).join('<br>')}</div><b>答案：${s.example.ans}</b></details>`:'';const d=slideShell(ch,`<div class="content"><section class="left"><div class="badge">${esc(s.sec)}・${esc(s.secName)}</div><h1>${s.title}</h1>${formula}<ul class="points">${points}</ul>${ex}</section><section><div class="visual-wrap"><div class="visual-host"></div></div>${s.caption?`<p class="caption">${s.caption}</p>`:''}</section></div>`);stage.appendChild(d);s.visual(d.querySelector('.visual-host'));if(window.MathJax?.typesetPromise)window.MathJax.typesetPromise([d])}
    document.querySelector('#counter').textContent=`${pos+1} / ${items.length}`;toc.querySelectorAll('.toc-item').forEach(b=>b.classList.toggle('active',+b.dataset.i===pos));
  }
  function go(n){pos=Math.max(0,Math.min(items.length-1,pos+n));render()}
  document.querySelector('#prev').onclick=()=>go(-1);document.querySelector('#next').onclick=()=>go(1);document.querySelector('#tocBtn').onclick=()=>toc.classList.toggle('open');document.querySelector('#presentBtn').onclick=()=>document.documentElement.requestFullscreen?.();document.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key===' ')go(1);if(e.key==='ArrowLeft')go(-1)});buildToc();render();
})();
